---
"on":
  push:
    branches: main

jobs:
  Setup_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Node cache
        uses: actions/cache@v3
        with:
          path: ./app/node_modules
          key: yarn-${{ hashFiles('app/yarn.lock') }}-${{ runner.os }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: YARN install
        working-directory: ./app
        run: yarn install

      - name: Test
        working-directory: ./app
        env:
          SQLITE_DB_LOCATION: /tmp/todos/test.db
        run: mkdir -p /tmp/todos && yarn test

  Build:
    needs: Setup_and_test
    runs-on: ubuntu-latest
    steps:
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image
        run: docker build -t temmojef/myapp:V1 ./
