---
"on": [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install depends
        run: |
          cd app
          yarn install --frozen-lockfile

      - name: Run test
        run: |
          cd app
          export SQLITE_DB_PATH="/tmp/todos/test.db"
          mkdir -p /tmp/todos
          chmod 777 /tmp/todos

          npm install dotenv
          SQLITE_DB_PATH="/tmp/todos/test.db" npm test
