---
"on": [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install depends
        run: |
          cd app
          yarn install --frozen-lockfile

      - name: Run test
        env:
          SQLITE_DB_LOCATION: /tmp/todos/test.db
        run: |
          cd app
          mkdir -p /tmp/todos
          yarn test
