---
"on":
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Node cache
        uses: actions/cache@v3
        with:
          path: ./app/node_modules
          key: yarn-${{ hashFiles('app/yarn.lock') }}-${{ runner.os }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: YARN install
        working-directory: ./app
        run: yarn install

      - name: Run test
        working-directory: ./app
        env:
          SQLITE_DB_LOCATION: /tmp/todos/test.db
        run: mkdir -p /tmp/todos && yarn test
